//------------------APP---------------------
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

//------------------HOTEL---------------------
export const NAME_COUNTRY = 'TICKET/NAME_COUNTRY'
export const START_DATE = 'TICKET/START_DATE'
export const END_DATE = 'TICKET/END_DATE'
export const SHOW_TICKETS = 'TICKET/SHOW_TICKETS'
export const RESERVED = 'TICKET/RESERVED'
export const FIND = 'TICKET/FIND'
export const DELETE = 'TICKET/DELETE'
export const COUNTRY = 'TICKET/COUNTRY'
export const SHOW_MY_TICKETS = 'TICKET/SHOW_MY_TICKETS'
export const TICKET_NAME = 'TICKET/TICKET_NAME'
export const ADDRESS = 'TICKET/ADDRESS'
export const LOCALITY = 'TICKET/LOCALITY'
export const PRICE = 'TICKET/PRICE'
export const PHOTO_URL = 'TICKET/PHOTO_URL'



export const REQUESTED_SUCCEEDED_TICKET = 'TICKET/REQUESTED_SUCCEEDED_TICKET'
export const REQUESTED_TICKET = 'TICKET/REQUESTED_TICKET'
export const REQUESTED_FAILED_TICKET = 'TICKET/REQUESTED_FAILED_TICKET'
export const REQUESTED_SUCCEEDED_CLOSE_TICKET = 'TICKET/REQUESTED_SUCCEEDED_CLOSE_TICKET'

//------------------USER---------------------
export const REQUESTED_SUCCEEDED_USER = 'USERS/REQUESTED_SUCCEEDED_USER'
export const REQUESTED_USER = 'USERS/REQUESTED_USER'
export const REQUESTED_FAILED_USER = 'USERS/REQUESTED_FAILED_USER'
export const REQUESTED_SUCCEEDED_CLOSE_USER = 'USERS/REQUESTED_SUCCEEDED_CLOSE_USER'

export const IS_AUTH = 'USERS/IS_AUTH'
export const USER_ID = 'USERS/USER_ID'
export const USER_NAME = 'USERS/USER_NAME'
export const USER_SURNAME = 'USERS/USER_SURNAME'
export const USER_EMAIL = 'USERS/USER_EMAIL'
export const USER_PASSWORD = 'USERS/USER_PASSWORD'
export const USER_ROLE = 'USERS/USER_ROLE'
export const CURRENT_PRICE = 'USERS/CURRENT_PRICE'


export const USER_GENDER = 'USERS/USER_GENDER'
export const USER_AGE = 'USERS/USER_AGE'
export const USER_DATE_OF_BIRTH = 'USERS/USER_DATE_OF_BIRTH'
export const USER_COUNTRY = 'USERS/USER_COUNTRY'
export const USER_PHONE = 'USERS/USER_PHONE'
export const SHOW_ALERT_USER = 'USERS/SHOW_ALERT'
export const HIDE_ALERT_USER = 'USERS/HIDE_ALERT'
export const CLEAR_USER = 'USERS/CLEAR_USER'
export const CHANGE = 'USERS/CHANGE'
export const ERROR = 'USERS/ERROR'
export const FLAG = 'USERS/FLAG'
export const SUCCESS = 'USERS/SUCCESS'
export const COUNT_HOTEL_TICKET = 'USERS/COUNT_HOTEL_TICKET'

//------------------ADMIN---------------------
export const REQUESTED_SUCCEEDED_ADMIN = 'ADMIN/REQUESTED_SUCCEEDED_ADMIN'
export const REQUESTED_ADMIN = 'ADMIN/REQUESTED_ADMIN'
export const REQUESTED_FAILED_ADMIN = 'ADMIN/REQUESTED_FAILED_ADMIN'
export const REQUESTED_SUCCEEDED_CLOSE_ADMIN = 'ADMIN/REQUESTED_SUCCEEDED_CLOSE_ADMIN'
export const CLEAR_ADMIN = 'ADMIN/CLEAR_ADMIN'