version: "3.9"
services:
  client:
    image: node:16-alpine3.11
    build: ./client1
    working_dir: /app
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    container_name: booking_client
    volumes:
      - ./client1:/app
    command: npm start
    depends_on:
      - server
  server:
    image: node:16-alpine3.11
    build: ./server
    restart: always
    container_name: booking_server
    command: npm run server
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: booking_db
    working_dir: /app
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=booking_db
    volumes:
      - ./booking_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db:
  server:
